//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;
namespace CredentialsDemo {
    
    
    public partial class Gateway {

        protected HtmlForm form1;
        protected HiddenField hidUser;
       
    }
}
