//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;
namespace CredentialsDemo {
    
    
    public partial class SiteMaster {

        protected ContentPlaceHolder HeadContent;
        protected HtmlGenericControl txt;
        protected Image Image1;
        protected HtmlGenericControl lnkHome;
        protected HtmlGenericControl lnkEntry;
        protected HtmlGenericControl lnkSearch;
        protected HtmlGenericControl lnkUserUserCreation;
        protected HtmlGenericControl lnkDataCreation;
        protected Label lbluserName;
        protected Label Label3;
        protected Label lblRole;
        protected Label Label1;
        protected Label lblVisitorCount;
        protected ContentPlaceHolder MainContent;
        protected Label dd;
    }
}
